CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE OR REPLACE FUNCTION generate_uuid() 
RETURNS UUID AS $$
BEGIN
    RETURN uuid_generate_v4();
END;
$$ LANGUAGE plpgsql;

INSERT INTO flightsapp.countries (id, name, iso_code) VALUES
(generate_uuid(), 'Afghanistan', 'AFG'),
(generate_uuid(), 'Albania', 'ALB'),
(generate_uuid(), 'Algeria', 'DZA'),
(generate_uuid(), 'Andorra', 'AND'),
(generate_uuid(), 'Angola', 'AGO'),
(generate_uuid(), 'Antigua and Barbuda', 'ATG'),
(generate_uuid(), 'Argentina', 'ARG'),
(generate_uuid(), 'Armenia', 'ARM'),
(generate_uuid(), 'Australia', 'AUS'),
(generate_uuid(), 'Austria', 'AUT'),
(generate_uuid(), 'Azerbaijan', 'AZE'),
(generate_uuid(), 'Bahamas', 'BHS'),
(generate_uuid(), 'Bahrain', 'BHR'),
(generate_uuid(), 'Bangladesh', 'BGD'),
(generate_uuid(), 'Barbados', 'BRB'),
(generate_uuid(), 'Belarus', 'BLR'),
(generate_uuid(), 'Belgium', 'BEL'),
(generate_uuid(), 'Belize', 'BLZ'),
(generate_uuid(), 'Benin', 'BEN'),
(generate_uuid(), 'Bhutan', 'BTN'),
(generate_uuid(), 'Bolivia', 'BOL'),
(generate_uuid(), 'Bosnia and Herzegovina', 'BIH'),
(generate_uuid(), 'Botswana', 'BWA'),
(generate_uuid(), 'Brazil', 'BRA'),
(generate_uuid(), 'Brunei', 'BRN'),
(generate_uuid(), 'Bulgaria', 'BGR'),
(generate_uuid(), 'Burkina Faso', 'BFA'),
(generate_uuid(), 'Burundi', 'BDI'),
(generate_uuid(), 'Cabo Verde', 'CPV'),
(generate_uuid(), 'Cambodia', 'KHM'),
(generate_uuid(), 'Cameroon', 'CMR'),
(generate_uuid(), 'Canada', 'CAN'),
(generate_uuid(), 'Central African Republic', 'CAF'),
(generate_uuid(), 'Chad', 'TCD'),
(generate_uuid(), 'Chile', 'CHL'),
(generate_uuid(), 'China', 'CHN'),
(generate_uuid(), 'Colombia', 'COL'),
(generate_uuid(), 'Comoros', 'COM'),
(generate_uuid(), 'Congo (Congo-Brazzaville)', 'COG'),
(generate_uuid(), 'Congo (Congo-Kinshasa)', 'COD'),
(generate_uuid(), 'Costa Rica', 'CRI'),
(generate_uuid(), 'Croatia', 'HRV'),
(generate_uuid(), 'Cuba', 'CUB'),
(generate_uuid(), 'Cyprus', 'CYP'),
(generate_uuid(), 'Czechia', 'CZE'),
(generate_uuid(), 'Denmark', 'DNK'),
(generate_uuid(), 'Djibouti', 'DJI'),
(generate_uuid(), 'Dominica', 'DMA'),
(generate_uuid(), 'Dominican Republic', 'DOM'),
(generate_uuid(), 'Ecuador', 'ECU'),
(generate_uuid(), 'Egypt', 'EGY'),
(generate_uuid(), 'El Salvador', 'SLV'),
(generate_uuid(), 'Equatorial Guinea', 'GNQ'),
(generate_uuid(), 'Eritrea', 'ERI'),
(generate_uuid(), 'Estonia', 'EST'),
(generate_uuid(), 'Eswatini', 'SWZ'),
(generate_uuid(), 'Ethiopia', 'ETH'),
(generate_uuid(), 'Fiji', 'FJI'),
(generate_uuid(), 'Finland', 'FIN'),
(generate_uuid(), 'France', 'FRA'),
(generate_uuid(), 'Gabon', 'GAB'),
(generate_uuid(), 'Gambia', 'GMB'),
(generate_uuid(), 'Georgia', 'GEO'),
(generate_uuid(), 'Germany', 'DEU'),
(generate_uuid(), 'Ghana', 'GHA'),
(generate_uuid(), 'Greece', 'GRC'),
(generate_uuid(), 'Grenada', 'GRD'),
(generate_uuid(), 'Guatemala', 'GTM'),
(generate_uuid(), 'Guinea', 'GIN'),
(generate_uuid(), 'Guinea-Bissau', 'GNB'),
(generate_uuid(), 'Guyana', 'GUY'),
(generate_uuid(), 'Haiti', 'HTI'),
(generate_uuid(), 'Honduras', 'HND'),
(generate_uuid(), 'Hungary', 'HUN'),
(generate_uuid(), 'Iceland', 'ISL'),
(generate_uuid(), 'India', 'IND'),
(generate_uuid(), 'Indonesia', 'IDN'),
(generate_uuid(), 'Iran', 'IRN'),
(generate_uuid(), 'Iraq', 'IRQ'),
(generate_uuid(), 'Ireland', 'IRL'),
(generate_uuid(), 'Italy', 'ITA'),
(generate_uuid(), 'Jamaica', 'JAM'),
(generate_uuid(), 'Japan', 'JPN'),
(generate_uuid(), 'Jordan', 'JOR'),
(generate_uuid(), 'Kazakhstan', 'KAZ'),
(generate_uuid(), 'Kenya', 'KEN'),
(generate_uuid(), 'Kiribati', 'KIR'),
(generate_uuid(), 'Democratic Peoples Republic of Korea', 'PRK'),
(generate_uuid(), 'Kuwait', 'KWT'),
(generate_uuid(), 'Kyrgyzstan', 'KGZ'),
(generate_uuid(), 'Laos', 'LAO'),
(generate_uuid(), 'Latvia', 'LVA'),
(generate_uuid(), 'Lebanon', 'LBN'),
(generate_uuid(), 'Lesotho', 'LSO'),
(generate_uuid(), 'Liberia', 'LBR'),
(generate_uuid(), 'Libya', 'LBY'),
(generate_uuid(), 'Liechtenstein', 'LIE'),
(generate_uuid(), 'Lithuania', 'LTU'),
(generate_uuid(), 'Luxembourg', 'LUX'),
(generate_uuid(), 'Madagascar', 'MDG'),
(generate_uuid(), 'Malawi', 'MWI'),
(generate_uuid(), 'Malaysia', 'MYS'),
(generate_uuid(), 'Maldives', 'MDV'),
(generate_uuid(), 'Mali', 'MLI'),
(generate_uuid(), 'Malta', 'MLT'),
(generate_uuid(), 'Marshall Islands', 'MHL'),
(generate_uuid(), 'Mauritania', 'MRT'),
(generate_uuid(), 'Mauritius', 'MUS'),
(generate_uuid(), 'Mexico', 'MEX'),
(generate_uuid(), 'Micronesia', 'FSM'),
(generate_uuid(), 'Moldova', 'MDA'),
(generate_uuid(), 'Monaco', 'MCO'),
(generate_uuid(), 'Mongolia', 'MNG'),
(generate_uuid(), 'Montenegro', 'MNE'),
(generate_uuid(), 'Morocco', 'MAR'),
(generate_uuid(), 'Mozambique', 'MOZ'),
(generate_uuid(), 'Myanmar', 'MMR'),
(generate_uuid(), 'Namibia', 'NAM'),
(generate_uuid(), 'Nauru', 'NRU'),
(generate_uuid(), 'Nepal', 'NPL'),
(generate_uuid(), 'Netherlands', 'NLD'),
(generate_uuid(), 'New Zealand', 'NZL'),
(generate_uuid(), 'Nicaragua', 'NIC'),
(generate_uuid(), 'Niger', 'NER'),
(generate_uuid(), 'Nigeria', 'NGA'),
(generate_uuid(), 'North Macedonia', 'MKD'),
(generate_uuid(), 'Norway', 'NOR'),
(generate_uuid(), 'Oman', 'OMN'),
(generate_uuid(), 'Pakistan', 'PAK'),
(generate_uuid(), 'Palau', 'PLW'),
(generate_uuid(), 'Palestine', 'PSE'),
(generate_uuid(), 'Panama', 'PAN'),
(generate_uuid(), 'Papua New Guinea', 'PNG'),
(generate_uuid(), 'Paraguay', 'PRY'),
(generate_uuid(), 'Peru', 'PER'),
(generate_uuid(), 'Philippines', 'PHL'),
(generate_uuid(), 'Poland', 'POL'),
(generate_uuid(), 'Portugal', 'PRT'),
(generate_uuid(), 'Qatar', 'QAT'),
(generate_uuid(), 'Romania', 'ROU'),
(generate_uuid(), 'Russia', 'RUS'),
(generate_uuid(), 'Rwanda', 'RWA'),
(generate_uuid(), 'Saint Kitts and Nevis', 'KNA'),
(generate_uuid(), 'Saint Lucia', 'LCA'),
(generate_uuid(), 'Saint Vincent and the Grenadines', 'VCT'),
(generate_uuid(), 'Samoa', 'WSM'),
(generate_uuid(), 'San Marino', 'SMR'),
(generate_uuid(), 'Sao Tome and Principe', 'STP'),
(generate_uuid(), 'Saudi Arabia', 'SAU'),
(generate_uuid(), 'Senegal', 'SEN'),
(generate_uuid(), 'Serbia', 'SRB'),
(generate_uuid(), 'Seychelles', 'SYC'),
(generate_uuid(), 'Sierra Leone', 'SLE'),
(generate_uuid(), 'Singapore', 'SGP'),
(generate_uuid(), 'Slovakia', 'SVK'),
(generate_uuid(), 'Slovenia', 'SVN'),
(generate_uuid(), 'Solomon Islands', 'SLB'),
(generate_uuid(), 'Somalia', 'SOM'),
(generate_uuid(), 'South Africa', 'ZAF'),
(generate_uuid(), 'Spain', 'ESP'),
(generate_uuid(), 'Sri Lanka', 'LKA'),
(generate_uuid(), 'Sudan', 'SDN'),
(generate_uuid(), 'Suriname', 'SUR'),
(generate_uuid(), 'Sweden', 'SWE'),
(generate_uuid(), 'Switzerland', 'CHE'),
(generate_uuid(), 'Syria', 'SYR'),
(generate_uuid(), 'Tajikistan', 'TJK'),
(generate_uuid(), 'Tanzania', 'TZA'),
(generate_uuid(), 'Thailand', 'THA'),
(generate_uuid(), 'Timor-Leste', 'TLS'),
(generate_uuid(), 'Togo', 'TGO'),
(generate_uuid(), 'Tonga', 'TON'),
(generate_uuid(), 'Trinidad and Tobago', 'TTO'),
(generate_uuid(), 'Tunisia', 'TUN'),
(generate_uuid(), 'Turkey', 'TUR'),
(generate_uuid(), 'Turkmenistan', 'TKM'),
(generate_uuid(), 'Tuvalu', 'TUV'),
(generate_uuid(), 'Uganda', 'UGA'),
(generate_uuid(), 'Ukraine', 'UKR'),
(generate_uuid(), 'United Arab Emirates', 'ARE'),
(generate_uuid(), 'United Kingdom', 'GBR'),
(generate_uuid(), 'United States', 'USA'),
(generate_uuid(), 'Uruguay', 'URY'),
(generate_uuid(), 'Uzbekistan', 'UZB'),
(generate_uuid(), 'Vanuatu', 'VUT'),
(generate_uuid(), 'Vatican City', 'VAT'),
(generate_uuid(), 'Venezuela', 'VEN'),
(generate_uuid(), 'Vietnam', 'VNM'),
(generate_uuid(), 'Yemen', 'YEM'),
(generate_uuid(), 'Zambia', 'ZMB'),
(generate_uuid(), 'Zimbabwe', 'ZWE');
