INSERT INTO countries (id, name, isoCode) VALUES
(UUID(), 'Afghanistan', 'AFG'),
(UUID(), 'Albania', 'ALB'),
(UUID(), 'Algeria', 'DZA'),
(UUID(), 'Andorra', 'AND'),
(UUID(), 'Angola', 'AGO'),
(UUID(), 'Antigua and Barbuda', 'ATG'),
(UUID(), 'Argentina', 'ARG'),
(UUID(), 'Armenia', 'ARM'),
(UUID(), 'Australia', 'AUS'),
(UUID(), 'Austria', 'AUT'),
(UUID(), 'Azerbaijan', 'AZE'),
(UUID(), 'Bahamas', 'BHS'),
(UUID(), 'Bahrain', 'BHR'),
(UUID(), 'Bangladesh', 'BGD'),
(UUID(), 'Barbados', 'BRB'),
(UUID(), 'Belarus', 'BLR'),
(UUID(), 'Belgium', 'BEL'),
(UUID(), 'Belize', 'BLZ'),
(UUID(), 'Benin', 'BEN'),
(UUID(), 'Bhutan', 'BTN'),
(UUID(), 'Bolivia', 'BOL'),
(UUID(), 'Bosnia and Herzegovina', 'BIH'),
(UUID(), 'Botswana', 'BWA'),
(UUID(), 'Brazil', 'BRA'),
(UUID(), 'Brunei', 'BRN'),
(UUID(), 'Bulgaria', 'BGR'),
(UUID(), 'Burkina Faso', 'BFA'),
(UUID(), 'Burundi', 'BDI'),
(UUID(), 'Cabo Verde', 'CPV'),
(UUID(), 'Cambodia', 'KHM'),
(UUID(), 'Cameroon', 'CMR'),
(UUID(), 'Canada', 'CAN'),
(UUID(), 'Central African Republic', 'CAF'),
(UUID(), 'Chad', 'TCD'),
(UUID(), 'Chile', 'CHL'),
(UUID(), 'China', 'CHN'),
(UUID(), 'Colombia', 'COL'),
(UUID(), 'Comoros', 'COM'),
(UUID(), 'Congo (Congo-Brazzaville)', 'COG'),
(UUID(), 'Congo (Congo-Kinshasa)', 'COD'),
(UUID(), 'Costa Rica', 'CRI'),
(UUID(), 'Croatia', 'HRV'),
(UUID(), 'Cuba', 'CUB'),
(UUID(), 'Cyprus', 'CYP'),
(UUID(), 'Czechia', 'CZE'),
(UUID(), 'Denmark', 'DNK'),
(UUID(), 'Djibouti', 'DJI'),
(UUID(), 'Dominica', 'DMA'),
(UUID(), 'Dominican Republic', 'DOM'),
(UUID(), 'Ecuador', 'ECU'),
(UUID(), 'Egypt', 'EGY'),
(UUID(), 'El Salvador', 'SLV'),
(UUID(), 'Equatorial Guinea', 'GNQ'),
(UUID(), 'Eritrea', 'ERI'),
(UUID(), 'Estonia', 'EST'),
(UUID(), 'Eswatini', 'SWZ'),
(UUID(), 'Ethiopia', 'ETH'),
(UUID(), 'Fiji', 'FJI'),
(UUID(), 'Finland', 'FIN'),
(UUID(), 'France', 'FRA'),
(UUID(), 'Gabon', 'GAB'),
(UUID(), 'Gambia', 'GMB'),
(UUID(), 'Georgia', 'GEO'),
(UUID(), 'Germany', 'DEU'),
(UUID(), 'Ghana', 'GHA'),
(UUID(), 'Greece', 'GRC'),
(UUID(), 'Grenada', 'GRD'),
(UUID(), 'Guatemala', 'GTM'),
(UUID(), 'Guinea', 'GIN'),
(UUID(), 'Guinea-Bissau', 'GNB'),
(UUID(), 'Guyana', 'GUY'),
(UUID(), 'Haiti', 'HTI'),
(UUID(), 'Honduras', 'HND'),
(UUID(), 'Hungary', 'HUN'),
(UUID(), 'Iceland', 'ISL'),
(UUID(), 'India', 'IND'),
(UUID(), 'Indonesia', 'IDN'),
(UUID(), 'Iran', 'IRN'),
(UUID(), 'Iraq', 'IRQ'),
(UUID(), 'Ireland', 'IRL'),
(UUID(), 'Israel', 'ISR'),
(UUID(), 'Italy', 'ITA'),
(UUID(), 'Jamaica', 'JAM'),
(UUID(), 'Japan', 'JPN'),
(UUID(), 'Jordan', 'JOR'),
(UUID(), 'Kazakhstan', 'KAZ'),
(UUID(), 'Kenya', 'KEN'),
(UUID(), 'Kiribati', 'KIR'),
(UUID(), 'Korea (North)', 'PRK'),
(UUID(), 'Korea (South)', 'KOR'),
(UUID(), 'Kuwait', 'KWT'),
(UUID(), 'Kyrgyzstan', 'KGZ'),
(UUID(), 'Laos', 'LAO'),
(UUID(), 'Latvia', 'LVA'),
(UUID(), 'Lebanon', 'LBN'),
(UUID(), 'Lesotho', 'LSO'),
(UUID(), 'Liberia', 'LBR'),
(UUID(), 'Libya', 'LBY'),
(UUID(), 'Liechtenstein', 'LIE'),
(UUID(), 'Lithuania', 'LTU'),
(UUID(), 'Luxembourg', 'LUX'),
(UUID(), 'Madagascar', 'MDG'),
(UUID(), 'Malawi', 'MWI'),
(UUID(), 'Malaysia', 'MYS'),
(UUID(), 'Maldives', 'MDV'),
(UUID(), 'Mali', 'MLI'),
(UUID(), 'Malta', 'MLT'),
(UUID(), 'Marshall Islands', 'MHL'),
(UUID(), 'Mauritania', 'MRT'),
(UUID(), 'Mauritius', 'MUS'),
(UUID(), 'Mexico', 'MEX'),
(UUID(), 'Micronesia', 'FSM'),
(UUID(), 'Moldova', 'MDA'),
(UUID(), 'Monaco', 'MCO'),
(UUID(), 'Mongolia', 'MNG'),
(UUID(), 'Montenegro', 'MNE'),
(UUID(), 'Morocco', 'MAR'),
(UUID(), 'Mozambique', 'MOZ'),
(UUID(), 'Myanmar', 'MMR'),
(UUID(), 'Namibia', 'NAM'),
(UUID(), 'Nauru', 'NRU'),
(UUID(), 'Nepal', 'NPL'),
(UUID(), 'Netherlands', 'NLD'),
(UUID(), 'New Zealand', 'NZL'),
(UUID(), 'Nicaragua', 'NIC'),
(UUID(), 'Niger', 'NER'),
(UUID(), 'Nigeria', 'NGA'),
(UUID(), 'North Macedonia', 'MKD'),
(UUID(), 'Norway', 'NOR'),
(UUID(), 'Oman', 'OMN'),
(UUID(), 'Pakistan', 'PAK'),
(UUID(), 'Palau', 'PLW'),
(UUID(), 'Palestine', 'PSE'),
(UUID(), 'Panama', 'PAN'),
(UUID(), 'Papua New Guinea', 'PNG'),
(UUID(), 'Paraguay', 'PRY'),
(UUID(), 'Peru', 'PER'),
(UUID(), 'Philippines', 'PHL'),
(UUID(), 'Poland', 'POL'),
(UUID(), 'Portugal', 'PRT'),
(UUID(), 'Qatar', 'QAT'),
(UUID(), 'Romania', 'ROU'),
(UUID(), 'Russia', 'RUS'),
(UUID(), 'Rwanda', 'RWA'),
(UUID(), 'Saint Kitts and Nevis', 'KNA'),
(UUID(), 'Saint Lucia', 'LCA'),
(UUID(), 'Saint Vincent and the Grenadines', 'VCT'),
(UUID(), 'Samoa', 'WSM'),
(UUID(), 'San Marino', 'SMR'),
(UUID(), 'Sao Tome and Principe', 'STP'),
(UUID(), 'Saudi Arabia', 'SAU'),
(UUID(), 'Senegal', 'SEN'),
(UUID(), 'Serbia', 'SRB'),
(UUID(), 'Seychelles', 'SYC'),
(UUID(), 'Sierra Leone', 'SLE'),
(UUID(), 'Singapore', 'SGP'),
(UUID(), 'Slovakia', 'SVK'),
(UUID(), 'Slovenia', 'SVN'),
(UUID(), 'Solomon Islands', 'SLB'),
(UUID(), 'Somalia', 'SOM'),
(UUID(), 'South Africa', 'ZAF'),
(UUID(), 'Spain', 'ESP'),
(UUID(), 'Sri Lanka', 'LKA'),
(UUID(), 'Sudan', 'SDN'),
(UUID(), 'Suriname', 'SUR'),
(UUID(), 'Sweden', 'SWE'),
(UUID(), 'Switzerland', 'CHE'),
(UUID(), 'Syria', 'SYR'),
(UUID(), 'Tajikistan', 'TJK'),
(UUID(), 'Tanzania', 'TZA'),
(UUID(), 'Thailand', 'THA'),
(UUID(), 'Timor-Leste', 'TLS'),
(UUID(), 'Togo', 'TGO'),
(UUID(), 'Tonga', 'TON'),
(UUID(), 'Trinidad and Tobago', 'TTO'),
(UUID(), 'Tunisia', 'TUN'),
(UUID(), 'Turkey', 'TUR'),
(UUID(), 'Turkmenistan', 'TKM'),
(UUID(), 'Tuvalu', 'TUV'),
(UUID(), 'Uganda', 'UGA'),
(UUID(), 'Ukraine', 'UKR'),
(UUID(), 'United Arab Emirates', 'ARE'),
(UUID(), 'United Kingdom', 'GBR'),
(UUID(), 'United States', 'USA'),
(UUID(), 'Uruguay', 'URY'),
(UUID(), 'Uzbekistan', 'UZB'),
(UUID(), 'Vanuatu', 'VUT'),
(UUID(), 'Vatican City', 'VAT'),
(UUID(), 'Venezuela', 'VEN'),
(UUID(), 'Vietnam', 'VNM'),
(UUID(), 'Yemen', 'YEM'),
(UUID(), 'Zambia', 'ZMB'),
(UUID(), 'Zimbabwe', 'ZWE');